# MinIO 配置
minio:
  #  endpoint: http://localhost:9000      # MinIO服务地址
  endpoint: http://118.89.125.143:9000      # MinIO服务地址
  #  fileHost: http://localhost:9000       # 文件地址host
  fileHost: http://118.89.125.143:9000       # 文件地址host
  bucketName: lzh-blog                      # 存储桶bucket名称
  accessKey: minioadmin                         # 用户名
  secretKey: minioadmin                    # 密码
  imgSize: 2048                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m
